name: Build And Deploy

on:
  push:
    branches: master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        script: |
          source /etc/profile
          cd ~/local/mongodb/mongodb-linux-x86_64-3.0.6/bin
          sudo ./mongod --dbpath=../../data/db  --fork --logpath=../../data/log
          cd ~/go/src/conch
          git pull
          go build
          nohup ./conch